Added gamecontrollerdb to remove loading exception
Eliminate this exception:

```
Failed to load mapping with original location "/gamecontrollerdb.txt", Falling back of SDL's built in mappings
java.lang.IllegalStateException: Failed to set SDL controller mappings! Falling back to build in SDL mappings.
        at com.studiohartman.jamepad.ControllerManager.addMappingsFromFile(ControllerManager.java:304)
        at com.studiohartman.jamepad.ControllerManager.initSDLGamepad(ControllerManager.java:95)
        at inkstain.input$fn__12082.invokeStatic(input.clj:8)
        at inkstain.input$fn__12082.invoke(input.clj:7)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:4222)
        at clojure.lang.Compiler$DefExpr.eval(Compiler.java:464)
        at clojure.lang.Compiler.eval(Compiler.java:7762)
        at clojure.lang.Compiler.load(Compiler.java:8223)
        at clojure.lang.RT.loadResourceScript(RT.java:401)
        at clojure.lang.RT.loadResourceScript(RT.java:392)
        at clojure.lang.RT.load(RT.java:479)
        at clojure.lang.RT.load(RT.java:444)
        at clojure.core$load$fn__6933.invoke(core.clj:6189)
        at clojure.core$load.invokeStatic(core.clj:6188)
        at clojure.core$load.doInvoke(core.clj:6172)
        at clojure.lang.RestFn.invoke(RestFn.java:411)
        at clojure.core$load_one.invokeStatic(core.clj:5961)
        at clojure.core$load_one.invoke(core.clj:5956)
        at clojure.core$load_lib$fn__6875.invoke(core.clj:6003)
        at clojure.core$load_lib.invokeStatic(core.clj:6002)
        at clojure.core$load_lib.doInvoke(core.clj:5981)
        at clojure.lang.RestFn.applyTo(RestFn.java:145)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6044)
        at clojure.core$load_libs.doInvoke(core.clj:6028)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6066)
        at clojure.core$require.doInvoke(core.clj:6066)
        at clojure.lang.RestFn.invoke(RestFn.java:1792)
        at inkstain.render$eval11908$loading__6814__auto____11909.invoke(render.clj:1)
        at inkstain.render$eval11908.invokeStatic(render.clj:1)
        at inkstain.render$eval11908.invoke(render.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7757)
        at clojure.lang.Compiler.eval(Compiler.java:7746)
        at clojure.lang.Compiler.load(Compiler.java:8223)
        at clojure.lang.RT.loadResourceScript(RT.java:401)
        at clojure.lang.RT.loadResourceScript(RT.java:392)
        at clojure.lang.RT.load(RT.java:479)
        at clojure.lang.RT.load(RT.java:444)
        at clojure.core$load$fn__6933.invoke(core.clj:6189)
        at clojure.core$load.invokeStatic(core.clj:6188)
        at clojure.core$load.doInvoke(core.clj:6172)
        at clojure.lang.RestFn.invoke(RestFn.java:411)
        at clojure.core$load_one.invokeStatic(core.clj:5961)
        at clojure.core$load_one.invoke(core.clj:5956)
        at clojure.core$load_lib$fn__6875.invoke(core.clj:6003)
        at clojure.core$load_lib.invokeStatic(core.clj:6002)
        at clojure.core$load_lib.doInvoke(core.clj:5981)
        at clojure.lang.RestFn.applyTo(RestFn.java:145)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6044)
        at clojure.core$load_libs.doInvoke(core.clj:6028)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6066)
        at clojure.core$require.doInvoke(core.clj:6066)
        at clojure.lang.RestFn.invoke(RestFn.java:3897)
        at inkstain.core$eval3529$loading__6814__auto____3530.invoke(core.clj:1)
        at inkstain.core$eval3529.invokeStatic(core.clj:1)
        at inkstain.core$eval3529.invoke(core.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7757)
        at clojure.lang.Compiler.eval(Compiler.java:7746)
        at clojure.lang.Compiler.load(Compiler.java:8223)
        at clojure.lang.RT.loadResourceScript(RT.java:401)
        at clojure.lang.RT.loadResourceScript(RT.java:392)
        at clojure.lang.RT.load(RT.java:479)
        at clojure.lang.RT.load(RT.java:444)
        at clojure.core$load$fn__6933.invoke(core.clj:6189)
        at clojure.core$load.invokeStatic(core.clj:6188)
        at clojure.core$load.doInvoke(core.clj:6172)
        at clojure.lang.RestFn.invoke(RestFn.java:411)
        at clojure.core$load_one.invokeStatic(core.clj:5961)
        at clojure.core$load_one.invoke(core.clj:5956)
        at clojure.core$load_lib$fn__6875.invoke(core.clj:6003)
        at clojure.core$load_lib.invokeStatic(core.clj:6002)
        at clojure.core$load_lib.doInvoke(core.clj:5981)
        at clojure.lang.RestFn.applyTo(RestFn.java:145)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6044)
        at clojure.core$load_libs.doInvoke(core.clj:6028)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6066)
        at clojure.core$require.doInvoke(core.clj:6066)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$serialized_require.invokeStatic(core.clj:6142)
        at clojure.core$requiring_resolve.invokeStatic(core.clj:6151)
        at clojure.core$requiring_resolve.invoke(core.clj:6145)
        at user$_main.invokeStatic(user.clj:38)
        at user$_main.doInvoke(user.clj:34)
        at clojure.lang.RestFn.invoke(RestFn.java:400)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:135)
        at clojure.lang.Var.applyTo(Var.java:707)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.main$main_opt.invokeStatic(main.clj:515)
        at clojure.main$main_opt.invoke(main.clj:511)
        at clojure.main$main.invokeStatic(main.clj:665)
        at clojure.main$main.doInvoke(main.clj:617)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.lang.Var.applyTo(Var.java:707)
        at clojure.main.main(main.java:40)
```